### ISSUE TITLE
Feature request get partial input (before Enter) in ainput

### ISSUE THREAD

**Issue by xtipacko** [vxgmichel/aioconsole#10]
I want to implement behavior similar to Cisco's "logging synchronous":
![capture_cli](https://user-images.githubusercontent.com/18727066/32537592-3394f368-c474-11e7-9e6b-b64976ea64c5.gif)
*correction to gif: And it doesn't interfere with my input

Here is an example of code:
```
import asyncio
from aioconsole import ainput

async def produce(queue, n):
    for x in range(1, n + 1):
        # produce an item
        #IS THERE ASYNC CLI INPUT LIKE THIS??? 
        word = await ainput('You produce: ')
        # put the item in the queue
        await queue.put(word)

    # indicate the producer is done
    await queue.put(None)


async def consume(queue):
    while True:
        # wait for an item from the producer
        item = await queue.get()
        if item is None:
            # the producer emits None to indicate that it is done
            break
        # process the item
        print(f'\r\nI consume {item}')
        # simulate i/o operation using sleep
        await asyncio.sleep(5)


loop = asyncio.get_event_loop()
queue = asyncio.Queue(loop=loop)
producer_coro = produce(queue, 30)
consumer_coro = consume(queue)
loop.run_until_complete(asyncio.gather(producer_coro, consumer_coro))
loop.close()
```

It will be cool to have a feature to get current "partial input" before ainput returns control and complete input to me...
It will allow me to copy this partial input to the end of my programm's output so user will have consistent 
 (not torn apart) propmpt+last partial input...

**Comment by vxgmichel** [comment]
Thank you for creating this issue, that's quite interesting!

Correct me if I'm wrong, but it seems like the feature you describe has little to do with partial inputs, and is instead very similar to the [`patch_stdout` option](http://python-prompt-toolkit.readthedocs.io/en/stable/pages/building_prompts.html#prompt-in-an-asyncio-application) of prompt-toolkit.

You might want to give this example a try:

```python
import string
import random
import asyncio

from prompt_toolkit import prompt_async


async def noise():
    s = string.punctuation
    while True:
        n = random.randint(10, 50)
        print(''.join(random.choice(s) for _ in range(n)))
        await asyncio.sleep(2 * random.random())


async def prompt():
    while True:
        result = await prompt_async('Say something: ', patch_stdout=True)
        print('You said: %s' % result)

if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.create_task(noise())
    loop.run_until_complete(prompt())
```

**Comment by xtipacko** [comment]
Wow, thanks :) Solved!, sorry for disturbance :))

**Comment by vxgmichel** [comment]
Yes, but this kind of feature seems quite hard to implement since it would involve ANSI escape sequences.
Thanks again!

**Comment by evgenart** [comment]
Well, I didn't need exactly prompt_async at the beggining. Cisco's behavior was good enough. (And I needed only to print propmpt+last_partial_input, each time I had an interference with output...)

**Comment by vxgmichel** [comment]
Oh I just understood what you meant! 

It is possible to do what you described using `aioconsole.get_standard_streams`:

```python
async def main(prompt='>>> '):
    reader, writer = await get_standard_streams()

    def safe_print(msg):
        line = '\n' + msg + '\n' + prompt
        writer.write(line.encode() + current)

    asyncio.ensure_future(noise(safe_print))

    while True:
        current = b''
        writer.write(prompt.encode())
        while b'\n' not in current:
            current += await reader.read(1)
        line = current.decode().rstrip('\n')
        writer.write('You said: {}\n'.format(line).encode())
```

The problem is, you'll have to find a way to make `stdin` unbuffered (in order to get notified for every new character), and that's quite tricky to do with python3.
