### ISSUE TITLE
Command history file support?

### ISSUE THREAD

**Issue by GeekDuanLian** [vxgmichel/aioconsole#100]
Hope to keep the old history in the new session.

**Comment by vxgmichel** [comment]
Hi @GeekDuanLian, thanks for the report

History support has been added for linux and macOS, see [v0.5.0](https://github.com/vxgmichel/aioconsole/releases/tag/v0.5.0) :tada:

**Comment by GeekDuanLian** [comment]
Thanks for your quick response!
I'm using cygwin under windows, but it works fine!
