### ISSUE TITLE
Why does print() have an impact on ainput()?

### ISSUE THREAD

**Issue by haukero** [vxgmichel/aioconsole#12]
I have the following simple test program to test ainput() behavior:

```python
import aioconsole
import asyncio

async def do_sleep(delay):
    while True:
        await asyncio.sleep(delay)
        print('Did sleep {:.2f} seconds.'.format(delay))

async def print_input(prompt):
    while True:
        s = await aioconsole.ainput(prompt)
        print('Input was:', s)


if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.create_task(do_sleep(10.0))
    loop.create_task(print_input('Enter string: '))
    loop.run_forever()
```

It is supposed to print the sleep message every 10 seconds and the input string after entering some text and pressing enter. This works well when I enter some text and press enter before the sleep message is printed in between, see below:

1. Input string is entered before sleep message is printed.

```
Enter string: abc
Input was: abc
```

2. Input string is entered after sleep message is printed.

```
Enter string: Did sleep 10.00 seconds.
abc
Input was: abc
```

However, when the sleep message interferes while entering some text, everything before the sleep message seems to get lost.

```
Enter string: aDid sleep 10.00 seconds.
bDid sleep 10.00 seconds.
cDid sleep 10.00 seconds.
d
Input was: d
```

So is this the correct behavior and if yes, why does it behave like this?

Thanks!

**Comment by vxgmichel** [comment]
Thanks for your report! I didn't manage to reproduce this issue on a linux terminal. Are you using windows and/or a special shell such as IDLE?

Also, can you give this code a try:

```python
import time
from concurrent.futures import ThreadPoolExecutor

def do_sleep(delay):
    while True:
        time.sleep(delay)
        print('Did sleep {:.2f} seconds.'.format(delay))

def print_input(prompt):
    while True:
        s = input(prompt)
        print('Input was:', s)


if __name__ == '__main__':
    with ThreadPoolExecutor() as pool:
        pool.submit(do_sleep, 1.)
        pool.submit(print_input, 'Enter string: ')
```

**Comment by haukero** [comment]
The reported problem occurred in PyCharm console on Mac OS. There, the same problem occurs with your changed code example using ThreadPoolExecutor. However, both code examples run fine in Mac OS terminal, so it might be just some strange behaviour of PyCharm console.

**Comment by vxgmichel** [comment]
Thanks for checking, I'm closing the issue then!
