### ISSUE TITLE
VIRTUAL_ENV appears to be ignored when using apython

### ISSUE THREAD

**Issue by rogpeppe** [vxgmichel/aioconsole#13]
When I set $VIRTUAL_ENV, the standard Python uses packages from there when importing, but apython does not seem to.

A sample transcript. I would expect the `__file__` members to print the same whether I'm running python3 or apython.

	rog@snazzy:~$ export VIRTUAL_ENV=/home/rog/src/python-libjuju/.tox/py35
	rog@snazzy:~$ PATH="$VIRTUAL_ENV/bin:$PATH"
	rog@snazzy:~$ python3
	Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
	[GCC 5.4.0 20160609] on linux
	Type "help", "copyright", "credits" or "license" for more information.
	>>> import juju
	>>> juju.__file__
	'/home/rog/src/python-libjuju/juju/__init__.py'
	>>> 
	rog@snazzy:~$ 
	rog@snazzy:~$ 
	rog@snazzy:~$ apython
	Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
	[GCC 5.4.0 20160609] on linux
	Type "help", "copyright", "credits" or "license" for more information.
	---
	This console is running in an asyncio event loop.
	It allows you to wait for coroutines using the 'await' syntax.
	Try: await asyncio.sleep(1, result=3)
	---
	>>> import juju
	>>> juju.__file__
	/usr/local/lib/python3.5/dist-packages/juju/__init__.py

This is running Ubuntu 16.04.

Linux snazzy 4.4.0-104-generic #127-Ubuntu SMP Mon Dec 11 12:16:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by vxgmichel** [comment]
Thanks for your report. Does that happen if you use `python3 -m aioconsole` instead of `apython`?

**Comment by rogpeppe** [comment]
You're right, I don't see that issue when running `python -m aioconsole`.
Is there some way we can fix that, because it would be nice if apython was as equivalent to python3 as possible, and that's a really subtle tripwire.

**Comment by vxgmichel** [comment]
Sorry for the late reply! As far as I understand, the proper way to fix this issue is simply to install `aioconsole` within your virtual env: `python -m pip install aioconsole`. At least that's how it works for conda environments.
