### ISSUE TITLE
typing ^D at apython prompt prints exception

### ISSUE THREAD

**Issue by rogpeppe** [vxgmichel/aioconsole#14]
In a normal python REPL, an EOF results in a clean exit.
In apython, I see the following:

	% apython
	Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
	[GCC 5.4.0 20160609] on linux
	Type "help", "copyright", "credits" or "license" for more information.
	---
	This console is running in an asyncio event loop.
	It allows you to wait for coroutines using the 'await' syntax.
	Try: await asyncio.sleep(1, result=3)
	---
	>>> 
	Exception ignored in: <bound method StandardStreamReader.__del__ of <StreamReader eof t=<_UnixReadPipeTransport closed fd=0 closed>>>
	Traceback (most recent call last):
	  File "/usr/local/lib/python3.5/dist-packages/aioconsole/stream.py", line 20, in __del__
	ValueError: I/O operation on closed file
	%

**Comment by vxgmichel** [comment]
Thanks for the report. This issue occurs in python 3.5 but disappeared in python 3.6.

**Comment by vxgmichel** [comment]
Fixed in 1c4df93, it will become visible in version 0.1.7. Thanks again!

**Comment by vxgmichel** [comment]
[v0.1.7](https://github.com/vxgmichel/aioconsole/releases/tag/v0.1.7) is out!
