### ISSUE TITLE
CI failure for python 3.8-dev

### ISSUE THREAD

**Issue by RyanWangGit** [vxgmichel/aioconsole#36]
I saw you disabled 3.8-dev branch for the moment, so I think it’s nice to open an issue for discussion if you don’t mind. :)

The problem is in `test_server` function, it seems that it doesn’t halt. `reader.readline()` doesn't seem to return.

**Comment by vxgmichel** [comment]
Right, thanks! :)

I don't have time to investigate the issue at the moment, but I'll make sure to have a look later.
