### ISSUE TITLE
How to add autocomplete when using ainput?

### ISSUE THREAD

**Issue by HatBoy** [vxgmichel/aioconsole#44]
I want to add autocomplete when using ainput like prompt_toolkit, or can I use ainput  with prompt_toolkit? Thanks !

**Comment by vxgmichel** [comment]
Hi @HatBoy,

If all you need is `ainput`, then I'd suggest to use prompt-toolkit async mode instead: 
```python
import asyncio
from prompt_toolkit import prompt
from prompt_toolkit.patch_stdout import patch_stdout
from prompt_toolkit.eventloop.defaults import use_asyncio_event_loop


async def main():
    use_asyncio_event_loop()
    with patch_stdout():
        result = await prompt('Tell me something: ', async_=True)
    print(result)

if __name__ == '__main__':
    asyncio.run(main())
```
See another example [here](https://github.com/prompt-toolkit/python-prompt-toolkit/blob/master/examples/prompts/asyncio-prompt.py).

Hope it helps!

**Comment by HatBoy** [comment]
Thank you very much, this is really what I need. @vxgmichel
