### ISSUE TITLE
Windows compatibility broken by fcntl import

### ISSUE THREAD

**Issue by chriscline** [vxgmichel/aioconsole#45]
The `import fcntl` line introduced in #43 broke Windows compatibility, since fcntl is not available on Windows. This import should probably be conditional on the platform.

**Comment by vxgmichel** [comment]
Ooops, I guess we really need to add some windows entries to our CI :sweat_smile: 

Thanks @chriscline for the report, I'll be releasing a new version today.

**Comment by vxgmichel** [comment]
Fixed with [v0.1.13](https://github.com/vxgmichel/aioconsole/releases/tag/v0.1.13), thanks again!
