### ISSUE TITLE
ainput on apython raise a NameError. (discord.py)

### ISSUE THREAD

**Issue by cyvax** [vxgmichel/aioconsole#47]
Hello

Some problem with ainput in discord.py inside apython terminal : 

```python
from discord.ext import commands
from aioconsole import aprint,ainput

client = commands.Bot(command_prefix=None)
usr_id = "115946460419194889" # usr_id

async def background_task():
    await client.wait_until_ready()
    channel = await client.get_user_info(usr_id)
    while not client.is_closed:
        console_input = await ainput("Input to send to channel: ")
        await client.send_message(channel, console_input)

client.loop.create_task(background_task())
client.run('token')
```

![image](https://user-images.githubusercontent.com/27162110/52739911-2f04eb80-2fd2-11e9-9684-2c5e4a671a34.png)

**Comment by vxgmichel** [comment]
Hi @cyvax,

Aren't you using `aexec` somewhere in your code?

**Comment by cyvax** [comment]
> Hi @cyvax,
> 
> Aren't you using `aexec` somewhere in your code?

No the whole code is at the top

**Comment by vxgmichel** [comment]
Then could you provide the full traceback?

**Comment by cyvax** [comment]
that's all : 

```Traceback (most recent call last):
  File "c:\users\cyvax\appdata\local\programs\python\python36-32\lib\site-packages\aioconsole\execute.py", line 95, in aexec
    result, new_local = yield from coro
  File "<aexec>", line 2, in __corofn
NameError: name 'foo' is not defined```

**Comment by cyvax** [comment]
something weird is that once the NameError is printed i can write something to send it is sent without any error.

**Comment by vxgmichel** [comment]
Does the following program work properly (make sure it runs at the same place in the same environment)?
```python
import asyncio
from aioconsole import aprint, ainput


async def main():
    result = await ainput("Input to send to channel: ")
    await aprint(result)

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

**Comment by cyvax** [comment]
Yes

```>>> Input to send to channel: foo
Traceback (most recent call last):
  File "c:\users\cyvax\appdata\local\programs\python\python36-32\lib\site-packages\aioconsole\execute.py", line 95, in aexec
    result, new_local = yield from coro
  File "<aexec>", line 2, in __corofn
NameError: name 'foo' is not defined```

**Comment by vxgmichel** [comment]
> Some problem with ainput in discord.py **inside apython terminal** :

Ooops I missed this piece of information. `ainput` should work when used directly in the console, but I expect weird things to happen if `ainput` is used within the program while running the console. What is your use case exactly?

**Comment by cyvax** [comment]
foo.py started with this command line :
```
apython foo.py
```
In a foo.bat

**Comment by vxgmichel** [comment]
I mean, why not use `python foo.py`? What does apython provide that you need in the context of the discord bot?

**Comment by cyvax** [comment]
I need aprint this is why i need to use apython

**Comment by vxgmichel** [comment]
> I need aprint this is why i need to use apython.
And i want a console side command with aioconsole

I'm sorry, I don't understand what you're trying to achieve. On one side, it seems like you're using standard input to communicate with your program (using `ainput`). On the other side you seem to want a python console, for debugging purpose, I guess? But since the both the program and the console need access to standard input, you'll eventually run into some conflicts. Maybe consider serving the access to the console through TCP instead:

    $ apython --serve localhost:8888 foo.py

**Comment by cyvax** [comment]
Yes, I know. I'm not very clear. Basically I want this: 

```python
======= Some bot Print =======
= Some bot log =
= Some bot log =
= Some bot log =
= Some bot log =
- Bot can print here -
Input to send to channel > # Waiting for input #
```

**Comment by vxgmichel** [comment]
Sorry about the late answer, I forgot about it :sweat_smile: 

> Basically I want this:
As far as I can tell,

**Comment by vxgmichel** [comment]
Sorry about the late answer, I forgot about it :sweat_smile: 

> Basically I want this:
> [...]

As far as I can tell, you simply want to run your code using python3 (and not `apython` which is mostly for debugging purposes):

    python3 foo.py

This should work for your example as far as I can tell.

Hope that helps!
