### ISSUE TITLE
Is there any way to read one character at the time?

### ISSUE THREAD

**Issue by tartavull** [vxgmichel/aioconsole#51]
I want to run a function when the arrow keys are pressed

**Comment by vxgmichel** [comment]
I really suggest looking into [ prompt toolkit ](https://python-prompt-toolkit.readthedocs.io) for this kind of advanced terminal tricks, in particular the following section: 

> [Adding custom key bindings](https://python-prompt-toolkit.readthedocs.io/en/master/pages/asking_for_input.html#adding-custom-key-bindings)
>
> By default, every prompt already has a set of key bindings which implements the usual Vi or Emacs behaviour. We can extend this by passing another KeyBindings instance to the key_bindings argument of the prompt() function or the PromptSession class.

Note that prompt-toolkit [does support asyncio](https://python-prompt-toolkit.readthedocs.io/en/master/pages/asking_for_input.html#prompt-in-an-asyncio-application).

Hope that helps!
