### ISSUE TITLE
Acknowledge aioconsole prompt limitations and advertise alternatives

### ISSUE THREAD

**Issue by iTosun** [vxgmichel/aioconsole#52]
It would be nice if it has the same style of tab completion as the normal python console.

**Comment by vxgmichel** [comment]
Hi @iTosun, thanks for the report!

Actually the apython script does provide tab completion, but only for local terminals on linux and osx. However, the limitation of aioconsole prompts are becoming more and more apparent. You might want to have a look at:
- [prompt-toolkit - autocompletion](https://python-prompt-toolkit.readthedocs.io/en/master/pages/asking_for_input.html#autocompletion)
- [prompt-toolkit - asyncio support](https://python-prompt-toolkit.readthedocs.io/en/stable/pages/advanced_topics/asyncio.html)
- [IPython - asynchronous REPL](https://ipython.readthedocs.io/en/stable/whatsnew/version7.html#autowait-asynchronous-repl)
- [IPython - embedding](https://ipython.readthedocs.io/en/stable/interactive/reference.html#embedding)

I think it's time to advertise prompt-toolkit and IPython capabilites on the readme file and the documentation.
