### ISSUE TITLE
BrokenPipeError on EOFError

### ISSUE THREAD

**Issue by jkerdreux-imt** [vxgmichel/aioconsole#87]
I use aioconsole embedded, but when I close the client (Ctrl-C), I get a BrokenPipeError. I think the error is here :

https://github.com/vxgmichel/aioconsole/blob/master/aioconsole/console.py#L195

Just removed the self.write() fix the issue.

Thanks for support

**Comment by vxgmichel** [comment]
Thanks for the report @jkerdreux-imt , it's fixed [version 0.3.3](https://github.com/vxgmichel/aioconsole/releases/tag/v0.3.3) :tada:

**Comment by jkerdreux-imt** [comment]
I'm using Asyncio + Gevent (I'm porting large piece of code from Gevent to Asyncio). I 'm still getting the BrokenPipeError, but it's trapped throught the _fatal_error handling of asyncio. 

Here the full traceback :

`Traceback (most recent call last):
  File "/home/jkx/Devel/xaal_env_0.7/lib/python3.10/site-packages/aioconsole/console.py", line 193, in _interact
    line = await self.raw_input(prompt)
  File "/home/jkx/Devel/xaal_env_0.7/lib/python3.10/site-packages/aioconsole/console.py", line 218, in raw_input
    return await self.ainput(prompt)
  File "/home/jkx/Devel/xaal_env_0.7/lib/python3.10/site-packages/aioconsole/console.py", line 88, in ainput
    return await stream.ainput(
  File "/home/jkx/Devel/xaal_env_0.7/lib/python3.10/site-packages/aioconsole/stream.py", line 242, in ainput
    raise EOFError
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jkx/.pyenv/versions/3.10.0/lib/python3.10/asyncio/selector_events.py", line 918, in write
    n = self._sock.send(data)
  File "/home/jkx/Devel/xaal_env_0.7/lib/python3.10/site-packages/gevent/_socketcommon.py", line 722, in send
    return self._sock.send(data, flags)
BrokenPipeError: [Errno 32] Broken pipe
`
The above traceback only appears when Asyncio debugging flag is set, but still embarassing. 

I'm wondering, if EOFError on a broken link, why keeping the self.writ("\n") ? 


Thanks for support.

**Comment by vxgmichel** [comment]
Sorry for the late reply @jkerdreux-imt ,

> I'm wondering, if `EOFError` on a broken link, why keeping the `self.write("\n")` ?

Mostly because that's how it's done in the `code` module :)

https://github.com/python/cpython/blob/c19c3a09618ac400538ee412f84be4c1196c7bab/Lib/code.py#L229

> I 'm still getting the BrokenPipeError, but it's trapped throught the _fatal_error handling of asyncio.

I don't really understand why this happens, the `BrokenPipeError` should be silenced by the `except OSError: pass` since the `BrokenPipeError` is a subclass of `OSError`. Could you investigate that? Or maybe provide a small example I could easily run on my machine to reproduce the issue?

Thanks for your help :)

**Comment by jkerdreux-imt** [comment]
You can close this issue. New versions fixed this issue. Thanks again for this code and your support.
